# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/azure-vote/Dockerfile'
        tags: |
          $(tag)
    - task: PublishPipelineArtifact@1
      displayName: Build an image in Artifact
      inputs:   
        artifactName: 'AzureVote'
        pathToPublish: 'd:\a\1\a'
    - task: Docker@2
      inputs:
        containerRegistry: 'DockerHubConn'
        repository: 'azurevote'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/azure-vote/Dockerfile'
    - task: DockerCompose@0
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: 'Azure subscription 1(17286c5c-7976-4042-8259-fc8f041cf62c)'
        azureContainerRegistry: '{"loginServer":"unyleyaeadacr1.azurecr.io", "id" : "/subscriptions/17286c5c-7976-4042-8259-fc8f041cf62c/resourceGroups/aks_unyleya_ead/providers/Microsoft.ContainerRegistry/registries/unyleyaeadacr1"}'
        dockerComposeFile: '$(Build.SourcesDirectory)/docker-compose.yml'
        action: 'Run a Docker Compose command'
        dockerComposeCommand: 'up'

